spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/crowdFundingDB
  application:
    name: PROJECT-SERVICE

server:
  port: 8080


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost